version: "2.2"

services:
  cypressV1Chrome:
      image: cypress/included:4.0.2
      ipc: host
      volumes:
        - ./:/tests/
        - /dev/shm:/dev/shm
      working_dir: /tests/TraditionalTests/TraditionalTestsV2
      command: --browser chrome
      mem_limit: 3072m
      cpu_count: 2
  cypressV1Firefox:
      image: cypress/included:4.0.2
      ipc: host
      volumes:
        - ./:/tests/
        - /dev/shm:/dev/shm
      working_dir: /tests/TraditionalTests/TraditionalTestsV2
      command: --browser firefox
      mem_limit: 3072m
      cpu_count: 2
    